#!/usr/bin/env bun
/**
 * Generate a compile-time server entry that statically imports Clay pages.
 *
 * Usage:
 *   bun docker/generate-server.ts ./app/pages > docker/compile-server.generated.ts
 *
 * Each page module must call `ui.page(...)`. Optional `pageMeta` exports are preserved.
 */
import { join } from 'path';

const appDir = process.argv[2];
if (!appDir) {
  console.error('Usage: bun docker/generate-server.ts <pages-dir>');
  process.exit(1);
}

const absDir = join(process.cwd(), appDir);
const relPrefix = appDir.replace(/\\/g, '/').replace(/\/$/, '');
const glob = new Bun.Glob('**/*.{ts,tsx}');
const files = [...glob.scanSync({ cwd: absDir })]
  .filter((f) => {
    const base = f.split('/').pop() ?? f;
    if (base.startsWith('_')) return false;
    if (base === 'index.ts' || base === 'index.tsx') return false;
    if (base.includes('.test.')) return false;
    return !f.split('/').some((part) => part.startsWith('_'));
  })
  .sort();

if (files.length === 0) {
  console.error(`No page modules found under ${absDir}`);
  process.exit(1);
}

const imports = files
  .map((f, i) => {
    const importPath = `./${relPrefix}/${f}`.replace(/\.tsx?$/, '');
    return `import * as pageMod${i} from '${importPath}';`;
  })
  .join('\n');

const sideEffects = files
  .map((_, i) => `void pageMod${i};`)
  .join('\n');

process.stdout.write(`/**
 * AUTO-GENERATED by docker/generate-server.ts — do not edit.
 */
import { ui } from '@close-by/clay';
${imports}

${sideEffects}

const port = Number(process.env.CLAY_PORT ?? 3000);
const title = process.env.CLAY_TITLE ?? 'Clay';
const clientDir = process.env.CLAY_CLIENT_DIR ?? '/app/client-dist';
const useAppShell = process.env.CLAY_APP === '1' || process.env.CLAY_APP === 'true';

const config = {
  port,
  title,
  clientDir,
  ...(useAppShell
    ? {
        app: {
          title,
          nav: ui.navFromPages(),
        },
      }
    : {}),
};

ui.run(config);
`);
